title: Junior Lobo
linkedin: https://www.linkedin.com/in/juniorlobo/
description: >- # this means to ignore newlines until "baseurl:"
   Front-end/Web Software Engineer
show_downloads: 'true'
google_analytics:
google_gtag: G-TF9HQ9YY2S
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
exclude: ["LICENSE.txt", "README.md"]
baseurl: ""
permalink: /:title/
languages: ['en', 'pt-br']
plugins:
   - jekyll-remote-theme # add this line to the plugins list if you already have one
   - jemoji
default_lang: "en"
exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]
